### ISSUE TITLE
Can data pre-processing scripts be written in Python3?

### ISSUE THREAD

**Issue by whikloj** [openelections/openelections-sources-in#3]
I'm assuming (I think I read this) that you want the code to be submitted with the pre-processed data for verification and possible re-use. But as these scripts are used only for specific formats of data and are generally not re-usable except in the same (or very similar) context, can they be in what ever we prefer to use? I have seen some seemingly written in R, so can they be written in Python 3?

**Comment by dwillis** [comment]
Hi @whikloj: Sure, they can be in Python 3, as long as that's noted somewhere.

**Comment by whikloj** [comment]
Thanks @dwillis. I am very new to this project and have been trying to read through the various docs. I'm guessing the major pain point is getting data from original format to your designated CSV format? I picked this repo at random as I'm not sure how much time I have but figured I'd pick something that might not otherwise get a lot of eyes on it and image based PDFs with handwritten adjustments seems like a pain that will need a lot of manual verification. If this is not a good place to start out, let me know.

**Comment by dwillis** [comment]
Yes, that's the major pain point. For Indiana, it's mostly data entry for precinct-level results, to be honest, so that may not be the best fit for your skills and interests. There are some parsing tasks in Kansas, Oregon and some other states if that interests you more.

**Comment by whikloj** [comment]
My interests related to this project is really around electoral transparency. So I have no specific desire to fulfill and am happy to help out where ever. I use with tesseract for work (though I'm not super skilled with it) and was thinking about how using it with an [automated genealogy](http://www.automatedgenealogy.com/) setup for verification/correction might be beneficial. Their system assigns you a page of hand-written census data, you transcribe it. Then that page is given to another volunteer to check your work. I was thinking about a TclTk app that allowed you to load a page and the HOCR of that page and allowed you to correct the HOCR. This still leaves a problem (for this Indiana data) of re-formatting it to a usable CSV. But at least it doesn't need to all be re-typed. I'll play around and see what I can figure out, if I start hitting walls I'll look at Kansas and Oregon.

**Comment by dwillis** [comment]
That would be super useful for us and a valuable contribution, so definitely would encourage your efforts in that direction. Thanks!
